name: Build Client
on: [push]
jobs:
  release:
    runs-on: [ubuntu-latest]
    steps:
      - name: Check out code
        uses: actions/checkout@v1
      - name: Extract Signature
        run: echo ${{secrets.KEY_FILE}} | base64 -d > $HOME/.android.jks
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - uses: subosito/flutter-action@v1
        with:
          channel: 'beta'
      - name: Build APK
        run: flutter build apk --target-platform android-arm
        env:
          KEY_PASS: ${{secrets.KEY_PASS}}
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: drc-${{ github.ref }}.apk
          path: build/app/outputs/flutter-apk/app-release.apk
      - name: create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: true
        if: github.event.created
      - name: Output Release URL File
        run: echo "${{ steps.create_release.outputs.upload_url }}" > release_url.txt
        if: github.event.created
      - name: Save Release URL File for publish
        uses: actions/upload-artifact@v1
        with:
          name: release_url
          path: release_url.txt
        if: github.event.created
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        include:
          - os: ubuntu-latest
            output-name: drc-linux
            platfrom: linux
          - os: macOS-latest
            output-name: drc-darwin
            platfrom: darwin
          - os: windows-latest
            output-name: drc-windows.exe
            platfrom: windows
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          channel: 'beta'
      - uses: cedx/setup-dart@v1.3.0
      - run: mkdir build
      - run: flutter pub get
      - run: dart2native bin/drc.dart -v -o build/${{ matrix.output-name }}
      - uses: actions/setup-go@v2
      - name: Install Go-Flutter Hover
        run: GO111MODULE=on go get -u -a github.com/go-flutter-desktop/hover
        shell: bash
      - run: hover build ${{ matrix.platfrom }}
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.platfrom }}
          path: go/build/outputs/${{ matrix.platfrom }}
      - name: Load Release URL File from release job
        uses: actions/download-artifact@v1
        with:
          name: release_url
        if: github.event.created
      - name: Get Release File Name & Upload URL
        id: get_release_info
        run: |
          value=`cat release_url/release_url.txt`
          echo ::set-output name=upload_url::$value
        shell: bash
        if: github.event.created
      - uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.get_release_info.outputs.upload_url }}
          asset_path: build/${{ matrix.output-name }}
          asset_name: ${{ matrix.output-name }}
          asset_content_type: application/octet-stream
        if: github.event.created
