name: Build Client
on: [push]
jobs:
  release:
    runs-on: [ubuntu-latest]
    steps:
      - name: Check Out Code
        uses: actions/checkout@v1
      - name: Extract Signature
        run: echo ${{secrets.KEY_FILE}} | base64 -d > $HOME/.android.jks
      - name: Setup JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Setup Flutter
        uses: subosito/flutter-action@v1
        with:
          channel: 'beta'
      - name: Build APK
        run: flutter build apk --target-platform android-arm
        env:
          KEY_PASS: ${{secrets.KEY_PASS}}
      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: drc-android
          path: build/app/outputs/flutter-apk/app-release.apk
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        include:
          - os: ubuntu-latest
            output-name: drc
            platfrom: linux
          - os: macOS-latest
            output-name: drc
            platfrom: darwin
          - os: windows-latest
            output-name: drc.exe
            platfrom: windows
    steps:
      - name: Check Out Code
        uses: actions/checkout@v2
      - name: Setup Flutter
        uses: subosito/flutter-action@v1
        with:
          channel: 'beta'
      - name: Setup Dart
        uses: cedx/setup-dart@v1.3.0
      - run: mkdir build
      - run: flutter pub get
      - run: dart2native bin/drc.dart -v -o build/${{ matrix.output-name }}
      - uses: actions/setup-go@v2
      - name: Install Go-Flutter Hover
        run: GO111MODULE=on go get -u -a github.com/go-flutter-desktop/hover
        shell: bash
      - run: $(go env GOPATH)/bin/hover build ${{ matrix.platfrom }}
      - name: Upload Client
        uses: actions/upload-artifact@v2
        with:
          name: drc-client-${{ matrix.platfrom }}
          path: go/build/outputs/${{ matrix.platfrom }}
      - name: Upload Command Tools
        uses: actions/upload-artifact@v2
        with:
          name: drc-cli-${{ matrix.platfrom }}
          path: build/${{ matrix.output-name }}