name: Build drc cli

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        include:
          - os: ubuntu-latest
            output-name: drc-linux
          - os: macOS-latest
            output-name: drc-darwin
          - os: windows-latest
            output-name: drc-windows.exe
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
      - uses: cedx/setup-dart@v1.3.0
      - run: mkdir build
      - run: flutter pub get
      - run: dart2native bin/drc.dart -v -o build/${{ matrix.output-name }}
      - uses: actions/create-release@v1
        id: create_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: true
        if: github.event.created
      - uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: build/${{ matrix.output-name }}
          asset_name: ${{ matrix.output-name }}
        if: github.event.created
