name: Build drc cli

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        include:
          - os: ubuntu-latest
            output-name: drc-linux
          - os: macOS-latest
            output-name: drc-darwin
          - os: windows-latest
            output-name: drc-windows.exe
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
      - uses: cedx/setup-dart@v1.3.0
      - run: mkdir build
      - run: flutter pub get
      - run: dart2native bin/drc.dart -v -o build/${{ matrix.output-name }}
      - uses: actions/upload-artifact@v1
        with:
          name: ${{ matrix.output-name }}
          path: build/${{ matrix.output-name }}
      - uses: meeDamian/github-release@1.0
        with:
          token: ${{secrets.GITHUB_TOKEN}}
          draft: true
          gzip: true
          files: build/${{ matrix.output-name }}
        if: github.event.created
