name: Direct Service Docker
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
      - uses: cedx/setup-dart@v1.3.0
      - run: flutter channel beta
      - run: flutter upgrade
      - run: flutter config --enable-web
      - run: flutter doctor
      - run: flutter pub get
      - run: dart2native bin/drcd.dart -v -o docker/drcd
      - run: flutter build web
      - run: mv build/web docker/web
      - run: echo $DOCKER_PASSWORD | docker login -u xausky --password-stdin
        env:
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build -t xausky/drcd:${GITHUB_REF##*/} docker
      - run: docker push xausky/drcd:${GITHUB_REF##*/}
      - run: mkdir -p aliyun-fc/build
      - run: cp docker/drcd aliyun-fc/bootstrap
      - run: cp -r docker/web aliyun-fc/build
      - name: Upload AliyunFC
        uses: actions/upload-artifact@v2
        with:
          name: drcd-aliyun-fc
          path: aliyun-fc
        continue-on-error: true